### ISSUE TITLE
NullReferenceException when opening the visualizer

### ISSUE THREAD

**Issue by Skyppid** [agileobjects/ReadableExpressions#49] opened 2020-01-10 07:57 UTC
`at AgileObjects.ReadableExpressions.Translations.TranslationBuffer.WriteToTranslation(String stringValue)
   at AgileObjects.ReadableExpressions.Translations.StaticTranslators.DefinitionsTranslator.WriteParametersToTranslation(MethodBase method, TranslationBuffer buffer)
   at AgileObjects.ReadableExpressions.Translations.StaticTranslators.DefinitionsTranslator.Translate(MethodInfo method)
   at AgileObjects.ReadableExpressions.Visualizers.Core.ExpressionVisualizerObjectSource.GetData(Object target, Stream outgoingData, Action`2 serializer)
   at AgileObjects.ReadableExpressions.Visualizers.Vs16ExpressionVisualizerObjectSource.GetData(Object target, Stream outgoingData)
   at Microsoft.VisualStudio.DebuggerVisualizers.DebuggeeSide.Impl.ClrCustomVisualizerDebuggeeHost.GetData(Object visualizedObject)`

When I try to visualize the following expression:
`{Method = {Boolean lambda_method(System.Runtime.CompilerServices.Closure, Core.Data.Models.Base.EntityBase, Core.Data.Models.Base.EntityBase)}}` for the following delegate signature: `Func<EntityBase, EntityBase, bool>`

Moreover when I click the visualizer icon on the debugger popup of the delegate, I end up with an empty window that only shows the signature **Func<x,y,z>**. When I expand that node and visualize the Method (not Target) field of that delegate, I get that exception.

**Comment by Skyppid** [comment] 2020-01-10 07:59
The code producing this issue is the following:

`                Func<EntityBase, EntityBase, bool> removeDelegate = Expression
                    .Lambda<Func<EntityBase, EntityBase, bool>>(
                        Expression.Call(Expression.Convert(parentEntity, entityType), removePair.removeMethod,
                            Expression.Convert(parentEntity, removePair.inputType)), parentEntity, entityExpression)`

**Comment by SteveWilkes** [comment] 2020-01-11 10:04
Thanks very much for reporting this - I'll fix it this weekend.

Cheers,

Steve

**Comment by SteveWilkes** [comment] 2020-01-13 19:10
Hello!

Looking at this, I've been unable to reproduce the issue. I've written [a dotnetfiddle]|(https://dotnetfiddle.net/1CTQrZ) creating and translating the lambda - please could you update it to throw the exception you've encountered?

Thanks!

Steve

**Comment by SteveWilkes** [comment] 2020-02-04 19:34
Closing as unable to reproduce and no further feedback.

**Closed by SteveWilkes** 2020-02-04 19:34 UTC
